repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # or the latest version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/pycqa/pylint
    rev: v3.2.6  # or the latest version
    hooks:
      - id: pylint
        additional_dependencies:
          - pylint==3.2.6  # or the version you want to use
